name: iCE40 synthesis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  synth-ice40:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Chryse
      uses: chryse-hdl/setup-chryse-action@main
      with:
        install-oss-cad-suite: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Elaborate and synthesise
      run: sbt 'run build ice40'
